Tabula/Controllers/ContentNoteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tabula.Models;

namespace Tabula.Controllers
{
    public class ContentNoteController : Controller
    {
        private TabulaDatabaseEntities db = new TabulaDatabaseEntities();

        // GET: /ContentNote/
        public ActionResult Index()
        {
            var contentnotes = db.ContentNotes.Include(c => c.Catalog).Include(c => c.UserProfile);
            return View(contentnotes.ToList());
        }

        // GET: /ContentNote/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContentNote contentnote = db.ContentNotes.Find(id);
            if (contentnote == null)
            {
                return HttpNotFound();
            }
            return View(contentnote);
        }

        // GET: /ContentNote/Create
        public ActionResult Create()
        {
            ViewBag.CatalogId = new SelectList(db.Catalogs, "Id", "Name");
            ViewBag.UserProfileId = new SelectList(db.UserProfiles, "Id", "UserName");
            return View();
        }

        // POST: /ContentNote/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,Content,CatalogId,UserProfileId,ImageUrl,CreateDate,LastUpdate,Like_Count,Comment_Count,Short_Content,Video_Url,Author")] ContentNote contentnote)
        {
            if (ModelState.IsValid)
            {
                contentnote.Id = Guid.NewGuid();
                db.ContentNotes.Add(contentnote);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CatalogId = new SelectList(db.Catalogs, "Id", "Name", contentnote.CatalogId);
            ViewBag.UserProfileId = new SelectList(db.UserProfiles, "Id", "UserName", contentnote.UserProfileId);
            return View(contentnote);
        }

        // GET: /ContentNote/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContentNote contentnote = db.ContentNotes.Find(id);
            if (contentnote == null)
            {
                return HttpNotFound();
            }
            ViewBag.CatalogId = new SelectList(db.Catalogs, "Id", "Name", contentnote.CatalogId);
            ViewBag.UserProfileId = new SelectList(db.UserProfiles, "Id", "UserName", contentnote.UserProfileId);
            return View(contentnote);
        }

        // POST: /ContentNote/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,Content,CatalogId,UserProfileId,ImageUrl,CreateDate,LastUpdate,Like_Count,Comment_Count,Short_Content,Video_Url,Author")] ContentNote contentnote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contentnote).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CatalogId = new SelectList(db.Catalogs, "Id", "Name", contentnote.CatalogId);
            ViewBag.UserProfileId = new SelectList(db.UserProfiles, "Id", "UserName", contentnote.UserProfileId);
            return View(contentnote);
        }

        // GET: /ContentNote/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContentNote contentnote = db.ContentNotes.Find(id);
            if (contentnote == null)
            {
                return HttpNotFound();
            }
            return View(contentnote);
        }

        // POST: /ContentNote/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            ContentNote contentnote = db.ContentNotes.Find(id);
            db.ContentNotes.Remove(contentnote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tabula/Controllers/UserProfileController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tabula.Models;

namespace Tabula.Controllers
{
    public class UserProfileController : Controller
    {
        private TabulaDatabaseEntities db = new TabulaDatabaseEntities();

        // GET: /UserProfile/
        public ActionResult Index()
        {
            return View(db.UserProfiles.ToList());
        }

        // GET: /UserProfile/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // GET: /UserProfile/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /UserProfile/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,UserName,Password,Brithdate,DisplayName")] UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                userprofile.Id = Guid.NewGuid();
                db.UserProfiles.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }

        // GET: /UserProfile/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // POST: /UserProfile/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,UserName,Password,Brithdate,DisplayName")] UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        // GET: /UserProfile/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        // POST: /UserProfile/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tabula/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- start: Meta -->
	<meta charset="utf-8" />
	<title>TABULA</title> 
	<meta name="description" content="Tabula Bootstrap Theme" />
	<meta name="keywords" content="Template, Theme, web, html5, css3, Bootstrap, pin, wall, responsive, fluid, retina" />
	<meta name="author" content="Quang Pham Soft" />
	<!-- end: Meta -->
	
	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	<!-- end: Mobile Specific -->
	
	<!-- start: Facebook Open Graph -->
	<meta property="og:title" content="" />
	<meta property="og:description" content="" />
	<meta property="og:type" content="" />
	<meta property="og:url" content="" />
	<meta property="og:image" content="" />


	<!-- end: Facebook Open Graph -->
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr") 
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" />
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Serif" />
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Boogaloo" />
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Economica:700,400italic" />

</head>
<body>
  <!--start: Header -->
	<header>
		
		<!--start: Container -->
		<div class="container">
			
			<!--start: Navigation -->
			<div class="navbar navbar-inverse">
	    		<div class="navbar-inner">
	          		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	          		</a> 
                    @Html.ActionLink("Pinterest", "Index", "Home", null, htmlAttributes: new { @class="brand" })
	          		<div class="nav-collapse collapse">
	            		<ul class="nav">
							<li class="active">@Html.ActionLink("Home", "Index", "Home")</li> 
							<li class="dropdown">
	                			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<b class="caret"></b></a>
	                			<ul class="dropdown-menu">
                                    <li>@Html.ActionLink("User","Index","UserProfile")</li>
                                    <li>@Html.ActionLink("Catalog","Index","Catalog")</li>
                                    <li>@Html.ActionLink("Note", "Index", "ContentNote")</li> 
	                			</ul>
	              			</li>
							<li><a href="portfolio.html">Portfolio</a></li>									
							<li><a href="pricing.html">Pricing</a></li>
							<li><a href="blog.html">Blog</a></li>
	              			<li><a href="contact.html">Contact</a></li>
							<li><a href="login.html">Login</a></li>
							<li><a href="register.html">Register</a></li>
                            <li><a href="about.html">About</a></li>
	            		</ul>
	          		</div>
	        	</div>
	      	</div>	
			<!--end: Navigation -->
			
		</div>
		<!--end: Container-->			
			
	</header>
	<!--end: Header-->
	<!--start: Container -->
	<div class="container">
		@RenderBody()		
		 
	</div>
	<!-- end: Wrapper  -->			

	<!-- start: Footer -->
	<div id="footer">
		
		<!-- start: Container -->
		<div class="container">
	
			<!-- start: Row -->
			<div class="row-fluid">

				<!-- start: About -->
				<div class="span3">
					
					<h3>creativeLabs</h3>

					<p>
						<i class="fa-icon-map-marker"></i> 30 South Park Avenue
					</p>
					<p>	
						<i class="fa-icon-map-marker"></i> San Francisco, CA 94108, USA
					</p>	
					<p>	
						<i class="fa-icon-phone"></i> Phone: (123) 456-7890
					</p>
					<p>	
						<i class="fa-icon-print"></i> Fax: +08 (123) 456-7890
					</p>
					<p>
						<i class="fa-icon-envelope"></i> Email: contact@companyname.com
					</p>
					<p>
						<i class="fa-icon-globe"></i> Web: companyname.com
					</p>
						
				</div>
				<!-- end: About -->

				<!-- start: Latest Tweets -->
				<div class="span3">
					
					<h3>Latest Tweets</h3>
					
					<ul id="twitter">
						
					</ul>

					<div class="clear"></div>
					
					
				</div>
				<!-- end: Latest Tweets -->

				<!-- start: Photo Stream -->
				<div class="span3">
					
					<h3>Flickr Photo Stream</h3>
					<div class="flickr-widget">
						<script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=12&display=latest&size=s&layout=x&source=user&user=29609591@N08"></script>
						<div class="clear"></div>
					</div>
					
				</div>
				<!-- end: Photo Stream -->
				
				<!-- start: Follow Us -->
				<div class="span3">
					
					<h3>Follow Us</h3>
					
					<a href="#" class="social-dribbble"></a>
					<a href="#" class="social-twitter"></a>
					<a href="#" class="social-flickr"></a>
					<a href="#" class="social-facebook"></a>
					<a href="#" class="social-linkedin"></a>
					<a href="#" class="social-vimeo"></a>
					<a href="#" class="social-youtube"></a>
					<a href="#" class="social-delicious"></a>
					<a href="#" class="social-rss"></a>
					<a href="#" class="social-picassa"></a>
					<a href="#" class="social-deviantart"></a>
					<a href="#" class="social-technorati"></a>
					<a href="#" class="social-stumbleupon"></a>
					<a href="#" class="social-appstore"></a>
					<a href="#" class="social-paypal"></a>
					<a href="#" class="social-myspace"></a>
					<a href="#" class="social-pinterest"></a>
					<a href="#" class="social-soundcloud"></a>
					<a href="#" class="social-behance"></a>
					<a href="#" class="social-instagram"></a>
					<a href="#" class="social-googleplus"></a>
	
				</div>
				<!-- end: Follow Us -->
				
			</div>
			<!-- end: Row -->
		
		</div>
		<!-- end: Container  -->	

	</div>
	<!-- end: Footer -->
	
	<!-- start: Under Footer -->
	<div id="under-footer">
		
		<!-- start: Container -->
		<div class="container">
			
			<!-- start: Row -->
			<div class="row-fluid">

				<!-- start: Under Footer Logo -->
				<div class="span2">
					<div id="under-footer-logo">
						<a class="brand" href="#">tabula</a>
					</div>
				</div>
				<!-- end: Under Footer Logo -->

				<!-- start: Under Footer Copyright -->
				<div class="span9">
					
					<div id="under-footer-copyright">
						&copy; 2012, <a href="http://clabs.co">creativeLabs</a>. Designed by <a href="http://clabs.co">creativeLabs</a> in Poland <img src="img/poland.png" alt="Poland" style="margin-top:-4px" />
					</div>
					
				</div>
				<!-- end: Under Footer Copyright -->

				<!-- start: Under Footer Back To Top -->
				<div class="span1">
						
					<div id="under-footer-back-to-top">
						<a href="#"></a>
					</div>
				
				</div>
				<!-- end: Under Footer Back To Top -->
			
			</div>
			<!-- end: Row -->
			
		</div>	
		<!-- end: Container  -->
		
	</div>
	<!-- end: Under Footer -->	
    
        
        

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Tabula/Views/Shared/_LayoutGreen.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <header>

        <!--start: Container -->
        <div class="container">

            <!--start: Navigation -->
            <div class="navbar navbar-inverse">
                <div class="navbar-inner">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    @Html.ActionLink("Pinterest", "Index", "Home", null, htmlAttributes: new { @class = "brand" })
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Features<b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("User", "Index", "UserProfile")</li>
                                    <li>@Html.ActionLink("Catalog", "Index", "Catalog")</li>
                                    <li>@Html.ActionLink("Note", "Index", "ContentNote")</li>
                                </ul>
                            </li>
                            <li><a href="portfolio.html">Portfolio</a></li>
                            <li><a href="pricing.html">Pricing</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="contact.html">Contact</a></li>
                            <li><a href="login.html">Login</a></li>
                            <li><a href="register.html">Register</a></li>
                            <li><a href="about.html">About</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--end: Navigation -->

        </div>
        <!--end: Container-->

    </header>
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>